"use strict";
let estaChovendo = false;
let idade = 25;
let nacionalidade = 'brasileira';
const colegas = ['lucas', 'fernanda'];
const tecnologias = ['html', 'css', 'js'];
const notas = [7, 8, 0, 10, 9];
const lista = ['leo', true, 19];
let idadeDaAna = 22;
idadeDaAna = 'vinte e cinco anos';
let tudo = 1;
tudo = 'sim';
tudo = true;
tudo = [1, 2, 3];
